# @package training
defaults: 
  - bevslots
  - perception_backbone: simplebev_v1
  - override encoder_backbone: savi_encoder_routes
  - _self_

bev:
  bevslots: 
    name: bevslots
  bevobject: 
    name: bevobject
  bevslotspercept: 
    name: bevslotspercept

perceive_slots: true
object_level_max_route_length: 2
object_level_max_num_objects: 0
use_object_level_route_in_slots: true
include_agent_in_object_level: false
split_long_routes: true
split_threshold: 10
include_traffic_lights_in_object_level: false
sort_by_distance: true
num_slots: ${training.encoder_backbone.savi.slot_dict.num_slots}
