scene_centroid:
    x: 0.0
    y: 1.0  # down 1 meter
    z: 0.0

bounds:
    X: [-20, 20]
    Z: [0, 40]
    Y: [-5, 5]

PIXELS_PER_METER_FOR_BEV: 5
PIXELS: 192

output_dims:
    Z: 192
    Y: 8
    X: 192

use_radar: False
use_lidar: False
use_metaradar: False
do_rgbcompress: True
rand_flip: False
latent_dim: 128
encoder_type: effb0
mean: 
    x: 0.485
    y: 0.456
    z: 0.406

std:
    x: 0.229
    y: 0.224
    z: 0.225


sensor_config:
-   x: 1.3
    y: 0.0
    z: 2.3
    roll: 0.0
    pitch: 0.0
    yaw: -60.0
    width: 320
    height: 160
    fov: 60
    id: rgb_left
-   x: 1.3
    y: 0.0
    z: 2.3
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
    width: 320
    height: 160
    fov: 60
    id: rgb_front
-   x: 1.3
    y: 0.0
    z: 2.3
    roll: 0.0
    pitch: 0.0
    yaw: 60.0
    width: 320
    height: 160
    fov: 60
    id: rgb_right

weight_path_rel: bin/simplebev_v1.pth
weight_path: ${user.working_dir}/${training.perception_backbone.weight_path_rel}

colorize: True
color: [173, 127, 168]