BENCHMARK: longest6
BENCHMARKNICKNAME: longest6micro
route_rel: leaderboard/data/longest6micro/longest6.xml
routes: ${user.working_dir}/${eval.route_rel}
scenarios_rel: leaderboard/data/longest6micro/eval_scenarios.json
scenarios: ${user.working_dir}/${eval.scenarios_rel}